name: CI pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Build-Angular:
    uses: ./.github/workflows/build-angular.yml

  Package:
    uses: ./.github/workflows/package.yml
    with:
      image_name: ${{ github.repository }}
      registry: "ghcr.io"
      mail_address:
      mail_port:
    secrets:
      email_username: ${{secrets.email_username}}
      email_password: ${{secrets.email_password}}
      mail_receiver: ${{ secrets.mail_receiver }}
      mail_sender: ${{ secrets.mail_sender }}