name: Nginx image creator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:

  create-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Installing Node
      working-directory: ./node
      run: npm install

    - name: RUN SuperTest API Testing
      working-directory: ./node
      run: npm test

    - name: Build Angular
      working-directory: ./angular
      run: |
        npm link @angular/cli
        ng build

    # - name: Build image
    #   run: docker build -t nginx-ang .

    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        push: true