name: Nginx image creator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  create-image:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Installing node
      working-directory: ./node
      run: npm install

    - name: RUN SuperTest API Testing
      working-directory: ./node
      run: npm test