# --------------------------------------------------------------
# GitHub Actions Workflow: build-angular
# 
# Description:
#   This workflow automates the process of building, testing and packaging
#   of the Angular app project.
#   It consists of a single job calling build-angular modular workflow
#
# Triggers:
#   - on: 
#       - push: Executes on a push to master.
#       - pull_request: Executes on a pull request to master.
#
# Jobs:
#   - build-Angular: Runs a callable workflow "build-angular", which
#     builds, tests and packages an image of an Angular app, served by Nginx
#     At the end of the workflow, calculates total time of execution and
#     sends an email notification with the outcome and total time.
#
# Notes:
#   - Requires the following secrets to be configured in the GitHub 
#     repository:
#       email_username: username for email authorisation
#       email_password: password for email authorisation
#       mail_receiver: email address of the notification receiver
#       mail_sender: displayed name of the notification sender
#   - Requires presence of the build-angular.yml workflow in
#     the GitHub workflows folder
#
# Expected Outcome:
#   - Successful execution of this workflow should result in [state 
#     the outcome, e.g., "a new Docker image published to Docker Hub" 
#     or "a deployed app on production servers"]. 
#
# --------------------------------------------------------------

name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-Angular:
    uses: ./.github/workflows/build-angular.yml
    
    with:
      image_name: ${{ github.repository }}
      registry: "ghcr.io"
      mail_address: "smtp.gmail.com"
      mail_port: 465
    
    secrets:
      email_username: ${{secrets.email_username}}
      email_password: ${{secrets.email_password}}
      mail_receiver: ${{ secrets.mail_receiver }}
      mail_sender: ${{ secrets.mail_sender }}
