name: Package

on:
  workflow_call:

    inputs:

      image_name:
        description: "Name of the uploaded image"
        required: true
        type: string

      registry:
        description: "Package upload registry"
        required: true
        type: string

    outputs:
      duration: ${{ steps.duration.outputs.duration }}

jobs:

  Package:
    runs-on: ubuntu-latest

    steps:

    - name: Login to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Get steps execution time
      if: always()
      id: duration
      uses: RockyIsHere/actions-calculate-log-time@v0.2.4
      env:
        GITHUB_TOKEN: ${{ github.token }}